### ISSUE TITLE
question on fitting EIS spectrum contains resistive-inductive loop

### ISSUE THREAD

**Issue by jianzuo** [jdhuang-csm/hybrid-drt#4]
Hello,
First of all, thanks for making this great library open-sourced!
I have a question regarding the DRT estimation with resistive-inductive loops.

I have tried based on the tutorial program by adding my spectrum and enabling 
`nonneg=False`
I do see the negative $\gamma$ in the DRT. What I do not understand is the resistive-inductive loop
should be fitted with a resistor and inductor in parallel circuit? According to the results given by 
`best_model.parameter_dict`
the resistive-inductive loops are also fit using HN circuits?

Thank you for checking this!

**Comment by jdhuang-csm** [comment]
Hi, thank you - I hope it is useful!

A resistive-inductive loop in the spectrum can be described by a resistor and inductor in parallel, but it can also equivalently be described by a negative resistance and a negative capacitance in parallel (with an offset to Zreal). Since this behavior can be described by a negative RC element, we can also use the RQ element or HN element to describe resistive-inductive loops that have varying degrees of dispersion and asymmetry. The resistance values and corresponding pseudo-capacitance values will simply be negative, rather than positive. 

If you want to use RC or RQ elements instead of HN elements, you can add the following argument to `DRT.dual_fit_eis`:

> `discrete_kw={'model_init_kw':{'drt_element': element_str}}`

where `element_str` is a string indicating the type of element to use for each DR peak. Options are "RC", "RQ", or "HN".

**Comment by jianzuo** [comment]
Hi,
Thanks a lot for the quick response and detailed explanation, they are very useful!
I see what you mean and agree that the behavior can be equivalent for R//L and -R//-C or -Q.
I come from a background of hydrogen fuel cells, and here I was trying to get a physical meaningful 
interpretation of the EIS spectra. That is why I was thinking of R//L for the resistive-inductive loop. For instance, 
from the deconvoluted DRT curve, we can identify the peaks and propose the equivalent circuits to provide the 
values of all elements which are physical meaningful.

But I am not sure that the negative resistor and pseudo-capacitance can be useful regarding the physical meaning aspect?

**Comment by jdhuang-csm** [comment]
I think that -R/-C or R/L representations can give similar interpretations; in my experience, it was more helpful to consider the time constant of the negative processes, rather than the capacitance or inductance. You may already have some literature more relevant to hydrogen fuel cells in mind, but I found these two papers helpful for considering possible phyiscal origins of this behavior:
https://www.sciencedirect.com/science/article/pii/S1388248118303084#s0010
https://journals.aps.org/prb/abstract/10.1103/PhysRevB.80.134202

**Comment by jianzuo** [comment]
Thank you very much for the explanation! I am going to check these papers to have a better understanding.

A small question on obtaining the time constant (just want to make sure my understanding it correct):
When the best model is fitted, In the results given by running `best_model.parameter_dict`, 
the time constant of RQ1 can be obtained by `np.e**(best_model.parameter_dict[''lntau_RQ1''])`?

**Comment by jdhuang-csm** [comment]
Yes, that's right! The ln(tau_0) values are stored in parameter_dict, so you can get tau_0 by exponentiating.

**Comment by jianzuo** [comment]
Thank you! I noticed that your library is relatively robust and works quite well on my data. 
Thanks again!

**Comment by jdhuang-csm** [comment]
Great, I'm glad to hear that! I'll close this issue.
